allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - oxlint-plugin-react-doctor@0.2.6
  - react-doctor@0.2.6
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - sharp
